--TEST--
MustacheAST rejects malformed resource-limit inputs and remains reusable
--SKIPIF--
<?php if (!extension_loaded('mustache')) die('skip '); ?>
--FILE--
<?php
function reportRejectedAST($label, $encoded) {
  try {
    new MustacheAST(base64_decode($encoded, true));
    echo $label, ":accepted\n";
  } catch (MustacheException $e) {
    echo $label, ':', $e->getMessage(), "\n";
  }
}

reportRejectedAST(
  'oversized-child-region',
  'TVUAAQAAAAAAAf////9NVQAQAQAABQAAAAAAAHRlc3QA'
);
reportRejectedAST(
  'deeply-nested',
  'TVUAAQAAAAAAAQAABBBNVQBAAAAAAgABAAAEAHgATVUAQAAAAAIAAQAAA/B4AE1VAEAAAAACAAEAAAPgeABNVQBAAAAAAgABAAAD0HgATVUAQAAAAAIAAQAAA8B4AE1VAEAAAAACAAEAAAOweABNVQBAAAAAAgABAAADoHgATVUAQAAAAAIAAQAAA5B4AE1VAEAAAAACAAEAAAOAeABNVQBAAAAAAgABAAADcHgATVUAQAAAAAIAAQAAA2B4AE1VAEAAAAACAAEAAANQeABNVQBAAAAAAgABAAADQHgATVUAQAAAAAIAAQAAAzB4AE1VAEAAAAACAAEAAAMgeABNVQBAAAAAAgABAAADEHgATVUAQAAAAAIAAQAAAwB4AE1VAEAAAAACAAEAAALweABNVQBAAAAAAgABAAAC4HgATVUAQAAAAAIAAQAAAtB4AE1VAEAAAAACAAEAAALAeABNVQBAAAAAAgABAAACsHgATVUAQAAAAAIAAQAAAqB4AE1VAEAAAAACAAEAAAKQeABNVQBAAAAAAgABAAACgHgATVUAQAAAAAIAAQAAAnB4AE1VAEAAAAACAAEAAAJgeABNVQBAAAAAAgABAAACUHgATVUAQAAAAAIAAQAAAkB4AE1VAEAAAAACAAEAAAIweABNVQBAAAAAAgABAAACIHgATVUAQAAAAAIAAQAAAhB4AE1VAEAAAAACAAEAAAIAeABNVQBAAAAAAgABAAAB8HgATVUAQAAAAAIAAQAAAeB4AE1VAEAAAAACAAEAAAHQeABNVQBAAAAAAgABAAABwHgATVUAQAAAAAIAAQAAAbB4AE1VAEAAAAACAAEAAAGgeABNVQBAAAAAAgABAAABkHgATVUAQAAAAAIAAQAAAYB4AE1VAEAAAAACAAEAAAFweABNVQBAAAAAAgABAAABYHgATVUAQAAAAAIAAQAAAVB4AE1VAEAAAAACAAEAAAFAeABNVQBAAAAAAgABAAABMHgATVUAQAAAAAIAAQAAASB4AE1VAEAAAAACAAEAAAEQeABNVQBAAAAAAgABAAABAHgATVUAQAAAAAIAAQAAAPB4AE1VAEAAAAACAAEAAADgeABNVQBAAAAAAgABAAAA0HgATVUAQAAAAAIAAQAAAMB4AE1VAEAAAAACAAEAAACweABNVQBAAAAAAgABAAAAoHgATVUAQAAAAAIAAQAAAJB4AE1VAEAAAAACAAEAAACAeABNVQBAAAAAAgABAAAAcHgATVUAQAAAAAIAAQAAAGB4AE1VAEAAAAACAAEAAABQeABNVQBAAAAAAgABAAAAQHgATVUAQAAAAAIAAQAAADB4AE1VAEAAAAACAAEAAAAgeABNVQBAAAAAAgABAAAAEHgATVUAAgAAAAIAAAAAAAB4AA=='
);

$mustache = new Mustache();
$ast = new MustacheAST((string) $mustache->parse('Hello {{name}}'));
var_dump($mustache->render($ast, array('name' => 'world')));
?>
--EXPECT--
oversized-child-region:Truncated serial child data
deeply-nested:Serial node nesting limit exceeded
string(11) "Hello world"
