name: CI

on:
    push:
        branches:
            - master
            - github-actions
            - ci
            - develop
    pull_request:
        branches:
            - master

permissions:
    contents: read

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    linux:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                PHP_VERSION:
                    - "8.3"
                    - "8.4"
                    - "8.5"
                COVERAGE: ["true", "false"]
        steps:
            - uses: actions/checkout@v7
              with:
                  submodules: recursive
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I'm putting everything in a FSCKING BASH SCRIPT
              env:
                  PHP_VERSION: ${{ matrix.PHP_VERSION }}
                  COVERAGE: ${{ matrix.COVERAGE }}
              run: bash ./.github/scripts/linux.sh
            - name: Coveralls
              if: matrix.COVERAGE == 'true'
              uses: coverallsapp/github-action@v2
              with:
                  file: coverage.info
                  format: lcov
                  flag-name: php-${{ matrix.PHP_VERSION }}
                  parallel: true

    docker:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                PHP_VERSION:
                    - "8.3"
                    - "8.4"
                    - "8.5"
                DOCKER_NAME:
                    - "alpine"
                    - "debian"
        steps:
            - uses: actions/checkout@v7
              with:
                submodules: recursive
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I am putting everything in a FSCKING BASH SCRIPT
              env:
                  PHP_VERSION: ${{ matrix.PHP_VERSION }}
                  DOCKER_NAME: ${{ matrix.DOCKER_NAME }}
              run: bash ./.github/scripts/docker.sh

    docker-fedora:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I am putting everything in a FSCKING BASH SCRIPT
              env:
                  DOCKER_NAME: fedora
                  TEST_PHP_EXECUTABLE: /usr/bin/php
              run: bash ./.github/scripts/docker.sh

    osx:
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                PHP_VERSION:
                    - "8.3"
                    - "8.4"
                    - "8.5"
        steps:
            - uses: actions/checkout@v7
              with:
                submodules: recursive
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I'm putting everything in a FSCKING BASH SCRIPT
              env:
                  PHP_VERSION: ${{ matrix.PHP_VERSION }}
              run: bash ./.github/scripts/osx.sh

    windows:
        name: "windows (PHP ${{ matrix.PHP.version }}, ${{ matrix.PHP_THREAD_SAFETY }}, x64)"
        runs-on: windows-2022
        strategy:
            fail-fast: false
            matrix:
                PHP:
                    - version: "8.1"
                      toolset: v142
                    - version: "8.5"
                      toolset: v143
                PHP_THREAD_SAFETY:
                    - nts
                    - ts
        steps:
            - uses: actions/checkout@v7

            - id: libmustache
              name: Build libmustache
              shell: pwsh
              run: ./.github/scripts/windows.ps1 -Toolset '${{ matrix.PHP.toolset }}'

            - name: Build and test extension
              uses: php/php-windows-builder/extension@36b2fc0672ba93bfa75bdd393edf2ef652961b4a
              with:
                  php-version: ${{ matrix.PHP.version }}
                  arch: x64
                  ts: ${{ matrix.PHP_THREAD_SAFETY }}
                  args: --enable-mustache --with-libmustache=${{ steps.libmustache.outputs.prefix }}

    pie:
        runs-on: ubuntu-latest
        permissions:
            attestations: read
            contents: read
        steps:
            - uses: actions/checkout@v7

            - name: Install and load with PIE
              env:
                  GH_TOKEN: ${{ github.token }}
              run: bash ./.github/scripts/pie.sh

    nix-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}
        steps:
            - uses: actions/checkout@v7
            - uses: cachix/install-nix-action@v31
            - id: set-matrix
              name: Generate Nix Matrix
              run: |
                  set -Eeu
                  matrix="$(nix eval --json '.#githubActions.matrix')"
                  echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

    nix:
        name: "nix (${{ matrix.name }})"
        runs-on: ${{ matrix.os }}
        needs: nix-matrix
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.nix-matrix.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v7

            - uses: cachix/install-nix-action@v31

            - name: Use nix-phps Cache
              uses: cachix/cachix-action@v17
              with:
                  name: fossar

            - run: nix build -L ".#${{ matrix.attr }}"

            - run: find -L result*; cp result-coverage/coverage.info coverage.info || true

            - name: Upload coverage reports to Codecov
              if: hashFiles('coverage.info') != ''
              uses: codecov/codecov-action@v7
              continue-on-error: true
              with:
                  files: coverage.info
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: jbboehr/php-mustache

            - name: Coveralls
              if: hashFiles('coverage.info') != ''
              uses: coverallsapp/github-action@v2
              continue-on-error: true
              with:
                  file: coverage.info
                  format: lcov
                  flag-name: ${{ matrix.name }}
                  parallel: true

    coveralls-finished:
        if: always() && !cancelled()
        needs:
            - linux
            - nix
        runs-on: ubuntu-latest
        steps:
            - name: Finish Coveralls build
              uses: coverallsapp/github-action@v2
              with:
                  parallel-finished: true
