name: docker

on:
    push:
        branches:
            - master
            - github-actions
            - ci
    pull_request:
        branches:
            - master

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                PHP_VERSION:
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0-rc"
                DOCKER_NAME:
                    - "alpine"
                    - "debian"
        steps:
            - uses: actions/checkout@v2
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I am putting everything in a FSCKING BASH SCRIPT
              env:
                  PHP_VERSION: ${{ matrix.PHP_VERSION }}
                  DOCKER_NAME: ${{ matrix.DOCKER_NAME }}
              run: bash ./.github/scripts/docker.sh
    fedora:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: I am tired of writing this shit in YAML and learning a new DSL for every CI service so I am putting everything in a FSCKING BASH SCRIPT
              env:
                  DOCKER_NAME: fedora
                  TEST_PHP_EXECUTABLE: /usr/bin/php
              run: bash ./.github/scripts/docker.sh
